function [fh,fh_udg,fh_uh] = fhat2d(nl,pg,udg,uh,param,time)
%FHAT2D
%    [FH,FH_UDG,FH_UH] = FHAT2D(NL,PG,UDG,UH,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Mar-2017 18:02:21
[ng,nc] = size(udg);
nch = 2;
nd = 2;
kappa = param{2};
mu = param{1};
nl1 = nl(:,1);
nl2 = nl(:,2);
one = ones(ng,1);
q11 = udg(:,3);
q12 = udg(:,5);
q21 = udg(:,4);
q22 = udg(:,6);
tau = param{3};
u1 = udg(:,1);
u2 = udg(:,2);
uh1 = uh(:,1);
uh2 = uh(:,2);
zero = zeros(ng,1);
t2 = q12.*q21;
t4 = q11.*q22;
t3 = t2-t4+1.0;
t5 = t2-t4;
t6 = 1.0./t5;
fh = [tau.*(u1-uh1)+nl1.*(mu.*q11-kappa.*q22.*t3+mu.*q22.*t6)+nl2.*(mu.*q12+kappa.*q21.*t3-(mu.*q21)./(t2-q11.*q22));tau.*(u2-uh2)+nl1.*(mu.*q21+kappa.*q12.*t3-mu.*q12.*t6)+nl2.*(mu.*q22-kappa.*q11.*t3+mu.*q11.*t6)];
if nargout > 1
    t7 = one.*tau;
    t8 = q22.^2;
    t9 = 1.0./(t2-t4).^2;
    t10 = mu.*t6;
    t11 = kappa.*q12.*q22;
    t12 = mu.*q12.*q22.*t9;
    t13 = t11+t12;
    t14 = q12.^2;
    t15 = q21.^2;
    t16 = kappa.*q21.*q22;
    t17 = mu.*q21.*q22.*t9;
    t18 = t16+t17;
    t19 = kappa.*t3;
    t20 = kappa.*q12.*q21;
    t21 = mu.*q12.*q21.*t9;
    t22 = -t10+t19+t20+t21;
    t23 = kappa.*q11.*q22;
    t24 = mu.*q11.*q22.*t9;
    t25 = kappa.*q11.*q21;
    t26 = mu.*q11.*q21.*t9;
    t27 = t25+t26;
    t28 = q11.^2;
    t29 = kappa.*q11.*q12;
    t30 = mu.*q11.*q12.*t9;
    t31 = t29+t30;
    fh_udg = [t7;zero;zero;t7;-nl2.*t18+nl1.*(mu+kappa.*t8+mu.*t8.*t9);-nl1.*t13+nl2.*(t10+t23+t24-kappa.*t3);-nl1.*t13+nl2.*t22;-nl2.*t31+nl1.*(mu+kappa.*t14+mu.*t9.*t14);-nl1.*t18+nl2.*(mu+kappa.*t15+mu.*t9.*t15);nl1.*t22-nl2.*t27;-nl2.*t27+nl1.*(t10-t19+t23+t24);-nl1.*t31+nl2.*(mu+kappa.*t28+mu.*t9.*t28)];
end
if nargout > 2
    fh_uh = [-t7;zero;zero;-t7];
end
fh = reshape(fh,ng,nch);
fh_udg = reshape(fh_udg,ng,nch,nc);
fh_uh = reshape(fh_uh,ng,nch,nch);
