function [f,f_udg] = flux2d(pg,udg,param,time)
%FLUX2D
%    [F,F_UDG] = FLUX2D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    18-Mar-2017 18:02:20
[ng,nc] = size(udg);
nch = 2;
nd = 2;
kappa = param{2};
mu = param{1};
q11 = udg(:,3);
q12 = udg(:,5);
q21 = udg(:,4);
q22 = udg(:,6);
zero = zeros(ng,1);
t2 = q12.*q21;
t4 = q11.*q22;
t3 = t2-t4+1.0;
t5 = t2-t4;
t6 = 1.0./t5;
f = [mu.*q11-kappa.*q22.*t3+(mu.*q22)./(t2-q11.*q22);mu.*q21+kappa.*q12.*t3-mu.*q12.*t6;mu.*q12+kappa.*q21.*t3-mu.*q21.*t6;mu.*q22-kappa.*q11.*t3+mu.*q11.*t6];
if nargout > 1
    t7 = q22.^2;
    t8 = 1.0./(t2-t4).^2;
    t9 = -kappa.*q12.*q22-mu.*q12.*q22.*t8;
    t10 = q12.^2;
    t11 = mu.*t6;
    t12 = -kappa.*q21.*q22-mu.*q21.*q22.*t8;
    t13 = kappa.*t3;
    t14 = kappa.*q12.*q21;
    t15 = mu.*q12.*q21.*t8;
    t16 = -t11+t13+t14+t15;
    t17 = q21.^2;
    t18 = kappa.*q11.*q22;
    t19 = mu.*q11.*q22.*t8;
    t20 = -kappa.*q11.*q12-mu.*q11.*q12.*t8;
    t21 = -kappa.*q11.*q21-mu.*q11.*q21.*t8;
    t22 = q11.^2;
    f_udg = [zero;zero;zero;zero;zero;zero;zero;zero;mu+kappa.*t7+mu.*t7.*t8;t9;t12;t11+t18+t19-kappa.*t3;t9;mu+kappa.*t10+mu.*t8.*t10;t16;t20;t12;t16;mu+kappa.*t17+mu.*t8.*t17;t21;t11-t13+t18+t19;t20;t21;mu+kappa.*t22+mu.*t8.*t22];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
