function [fh,fh_udg,fh_uh] = fhat3d(nl,pg,udg,uh,param,time)
%FHAT3D
%    [FH,FH_UDG,FH_UH] = FHAT3D(NL,PG,UDG,UH,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    19-Mar-2017 09:59:48
[ng,nc] = size(udg);
nch = 3;
nd = 3;
lambda = param{2};
mu = param{1};
nl1 = nl(:,1);
nl2 = nl(:,2);
nl3 = nl(:,3);
one = ones(ng,1);
q11 = udg(:,4);
q12 = udg(:,7);
q13 = udg(:,10);
q21 = udg(:,5);
q22 = udg(:,8);
q23 = udg(:,11);
q31 = udg(:,6);
q32 = udg(:,9);
q33 = udg(:,12);
tau = param{3};
u1 = udg(:,1);
u2 = udg(:,2);
u3 = udg(:,3);
uh1 = uh(:,1);
uh2 = uh(:,2);
uh3 = uh(:,3);
zero = zeros(ng,1);
t2 = q11+q22+q33+3.0;
t3 = lambda.*t2;
t4 = q12+q21;
t5 = q13+q31;
t6 = q23+q32;
fh = [nl1.*(t3+mu.*(q11+1.0).*2.0)+tau.*(u1-uh1)+mu.*nl2.*t4+mu.*nl3.*t5;nl2.*(t3+mu.*(q22+1.0).*2.0)+tau.*(u2-uh2)+mu.*nl1.*t4+mu.*nl3.*t6;nl3.*(t3+mu.*(q33+1.0).*2.0)+tau.*(u3-uh3)+mu.*nl1.*t5+mu.*nl2.*t6];
if nargout > 1
    t7 = one.*tau;
    t8 = mu.*nl1.*one;
    t9 = mu.*nl2.*one;
    t10 = mu.*2.0;
    t11 = lambda+t10;
    t12 = lambda.*nl3.*one;
    t13 = mu.*nl3.*one;
    t14 = lambda.*nl1.*one;
    t15 = lambda.*nl2.*one;
    fh_udg = [t7;zero;zero;zero;t7;zero;zero;zero;t7;nl1.*one.*t11;t15;t12;t9;t8;zero;t13;zero;t8;t9;t8;zero;t14;nl2.*one.*t11;t12;zero;t13;t9;t13;zero;t8;zero;t13;t9;t14;t15;nl3.*one.*t11];
end
if nargout > 2
    fh_uh = [-t7;zero;zero;zero;-t7;zero;zero;zero;-t7];
end
fh = reshape(fh,ng,nch);
fh_udg = reshape(fh_udg,ng,nch,nc);
fh_uh = reshape(fh_uh,ng,nch,nch);
