function [f,f_udg] = flux3d(pg,udg,param,time)
%FLUX3D
%    [F,F_UDG] = FLUX3D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    19-Mar-2017 09:59:45
[ng,nc] = size(udg);
nch = 3;
nd = 3;
lambda = param{2};
mu = param{1};
one = ones(ng,1);
q11 = udg(:,4);
q12 = udg(:,7);
q13 = udg(:,10);
q21 = udg(:,5);
q22 = udg(:,8);
q23 = udg(:,11);
q31 = udg(:,6);
q32 = udg(:,9);
q33 = udg(:,12);
zero = zeros(ng,1);
t2 = q12+q21;
t3 = mu.*t2;
t4 = q11+q22+q33+3.0;
t5 = lambda.*t4;
t6 = q13+q31;
t7 = mu.*t6;
t8 = q23+q32;
t9 = mu.*t8;
f = [t5+mu.*(q11+1.0).*2.0;t3;t7;t3;t5+mu.*(q22+1.0).*2.0;t9;t7;t9;t5+mu.*(q33+1.0).*2.0];
if nargout > 1
    t10 = lambda.*one;
    t11 = mu.*one;
    t12 = mu.*2.0;
    t13 = lambda+t12;
    t14 = one.*t13;
    f_udg = [zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;t14;zero;zero;zero;t10;zero;zero;zero;t10;zero;t11;zero;t11;zero;zero;zero;zero;zero;zero;zero;t11;zero;zero;zero;t11;zero;zero;zero;t11;zero;t11;zero;zero;zero;zero;zero;t10;zero;zero;zero;t14;zero;zero;zero;t10;zero;zero;zero;zero;zero;t11;zero;t11;zero;zero;zero;t11;zero;zero;zero;t11;zero;zero;zero;zero;zero;zero;zero;t11;zero;t11;zero;t10;zero;zero;zero;t10;zero;zero;zero;t14];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
