function [f,f_udg] = flux2d(pg,udg,param,time)
%FLUX2D
%    [F,F_UDG] = FLUX2D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    19-Mar-2017 09:59:35
[ng,nc] = size(udg);
nch = 2;
nd = 2;
lambda = param{2};
mu = param{1};
one = ones(ng,1);
q11 = udg(:,3);
q12 = udg(:,5);
q21 = udg(:,4);
q22 = udg(:,6);
zero = zeros(ng,1);
t2 = q12+q21;
t3 = mu.*t2;
t4 = q11+q22+2.0;
t5 = lambda.*t4;
f = [t5+mu.*(q11+1.0).*2.0;t3;t3;t5+mu.*(q22+1.0).*2.0];
if nargout > 1
    t6 = mu.*one;
    t7 = lambda.*one;
    t8 = mu.*2.0;
    t9 = lambda+t8;
    t10 = one.*t9;
    f_udg = [zero;zero;zero;zero;zero;zero;zero;zero;t10;zero;zero;t7;zero;t6;t6;zero;zero;t6;t6;zero;t7;zero;zero;t10];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
