function [f,f_udg] = flux2d(pg,udg,param,time)
%FLUX2D
%    [F,F_UDG] = FLUX2D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    19-Mar-2017 09:34:27
[ng,nc] = size(udg);
nch = 2;
nd = 2;
lambda = param{2};
mu = param{1};
q11 = udg(:,3);
q12 = udg(:,5);
q21 = udg(:,4);
q22 = udg(:,6);
zero = zeros(ng,1);
t2 = q11.^2;
t3 = t2.*(1.0./2.0);
t4 = q21.^2;
t5 = t4.*(1.0./2.0);
t6 = t3+t5-1.0./2.0;
t7 = mu.*t6.*2.0;
t8 = q12.^2;
t9 = t8.*(1.0./2.0);
t10 = q22.^2;
t11 = t10.*(1.0./2.0);
t12 = t3+t5+t9+t11-1.0;
t13 = lambda.*t12;
t14 = t7+t13;
t15 = q11.*q12.*(1.0./2.0);
t16 = q21.*q22.*(1.0./2.0);
t17 = t15+t16;
t18 = t9+t11-1.0./2.0;
t19 = mu.*t18.*2.0;
t20 = t13+t19;
f = [q11.*t14+mu.*q12.*t17.*2.0;q21.*t14+mu.*q22.*t17.*2.0;q12.*t20+mu.*q11.*t17.*2.0;q22.*t20+mu.*q21.*t17.*2.0];
if nargout > 1
    t21 = lambda.*q11;
    t22 = mu.*q11.*2.0;
    t23 = t21+t22;
    t24 = mu.*q12.*q22;
    t25 = lambda.*q21;
    t26 = mu.*q21.*2.0;
    t27 = t25+t26;
    t28 = mu.*t17.*2.0;
    t29 = lambda.*q11.*q12;
    t30 = mu.*q11.*q12;
    t31 = t28+t29+t30;
    t32 = lambda.*q12.*q21;
    t33 = mu.*q11.*q22;
    t34 = t32+t33;
    t35 = lambda.*q12;
    t36 = mu.*q12.*2.0;
    t37 = t35+t36;
    t38 = lambda.*q11.*q22;
    t39 = mu.*q12.*q21;
    t40 = t38+t39;
    t41 = lambda.*q21.*q22;
    t42 = mu.*q21.*q22;
    t43 = t28+t41+t42;
    t44 = mu.*q11.*q21;
    t45 = lambda.*q22;
    t46 = mu.*q22.*2.0;
    t47 = t45+t46;
    f_udg = [zero;zero;zero;zero;zero;zero;zero;zero;t7+t13+mu.*t8+q11.*t23;t24+q21.*t23;t31;t40;t24+q11.*t27;t7+t13+mu.*t10+q21.*t27;t34;t43;t31;t34;t13+t19+mu.*t2+q12.*t37;t44+q22.*t37;t40;t43;t44+q12.*t47;t13+t19+mu.*t4+q22.*t47];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
