function [fh,fh_udg,fh_uh] = fhat3d(nl,pg,udg,uh,param,time)
%FHAT3D
%    [FH,FH_UDG,FH_UH] = FHAT3D(NL,PG,UDG,UH,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Jul-2017 23:11:13
[ng,nc] = size(udg);
nch = 3;
nd = 3;
nl1 = nl(:,1);
nl2 = nl(:,2);
nl3 = nl(:,3);
one = ones(ng,1);
param1 = param{1};
param2 = param{2};
param3 = param{3};
u1 = udg(:,1);
u2 = udg(:,2);
u3 = udg(:,3);
u4 = udg(:,4);
u5 = udg(:,5);
u6 = udg(:,6);
u7 = udg(:,7);
u8 = udg(:,8);
u9 = udg(:,9);
u10 = udg(:,10);
u11 = udg(:,11);
u12 = udg(:,12);
uh1 = uh(:,1);
uh2 = uh(:,2);
uh3 = uh(:,3);
zero = zeros(ng,1);
t2 = u4+u8+u12;
t3 = param2.*t2;
t4 = u5+u7;
t5 = u6+u10;
t6 = u9+u11;
fh = [param3.*(u1-uh1)+nl1.*(t3+param1.*u4.*2.0)+nl2.*param1.*t4+nl3.*param1.*t5;param3.*(u2-uh2)+nl2.*(t3+param1.*u8.*2.0)+nl1.*param1.*t4+nl3.*param1.*t6;param3.*(u3-uh3)+nl3.*(t3+param1.*u12.*2.0)+nl1.*param1.*t5+nl2.*param1.*t6];
if nargout > 1
    t7 = one.*param3;
    t8 = nl1.*one.*param1;
    t9 = nl2.*one.*param1;
    t10 = param1.*2.0;
    t11 = param2+t10;
    t12 = nl3.*one.*param2;
    t13 = nl3.*one.*param1;
    t14 = nl1.*one.*param2;
    t15 = nl2.*one.*param2;
    fh_udg = [t7;zero;zero;zero;t7;zero;zero;zero;t7;nl1.*one.*t11;t15;t12;t9;t8;zero;t13;zero;t8;t9;t8;zero;t14;nl2.*one.*t11;t12;zero;t13;t9;t13;zero;t8;zero;t13;t9;t14;t15;nl3.*one.*t11];
end
if nargout > 2
    fh_uh = [-t7;zero;zero;zero;-t7;zero;zero;zero;-t7];
end
fh = reshape(fh,ng,nch);
fh_udg = reshape(fh_udg,ng,nch,nc);
fh_uh = reshape(fh_uh,ng,nch,nch);
