function [f,f_udg] = flux3d(pg,udg,param,time)
%FLUX3D
%    [F,F_UDG] = FLUX3D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Jul-2017 23:11:10
[ng,nc] = size(udg);
nch = 3;
nd = 3;
one = ones(ng,1);
param1 = param{1};
param2 = param{2};
u4 = udg(:,4);
u5 = udg(:,5);
u6 = udg(:,6);
u7 = udg(:,7);
u8 = udg(:,8);
u9 = udg(:,9);
u10 = udg(:,10);
u11 = udg(:,11);
u12 = udg(:,12);
zero = zeros(ng,1);
t2 = u5+u7;
t3 = param1.*t2;
t4 = u4+u8+u12;
t5 = param2.*t4;
t6 = u6+u10;
t7 = param1.*t6;
t8 = u9+u11;
t9 = param1.*t8;
f = [t5+param1.*u4.*2.0;t3;t7;t3;t5+param1.*u8.*2.0;t9;t7;t9;t5+param1.*u12.*2.0];
if nargout > 1
    t10 = one.*param2;
    t11 = one.*param1;
    t12 = param1.*2.0;
    t13 = param2+t12;
    t14 = one.*t13;
    f_udg = [zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;t14;zero;zero;zero;t10;zero;zero;zero;t10;zero;t11;zero;t11;zero;zero;zero;zero;zero;zero;zero;t11;zero;zero;zero;t11;zero;zero;zero;t11;zero;t11;zero;zero;zero;zero;zero;t10;zero;zero;zero;t14;zero;zero;zero;t10;zero;zero;zero;zero;zero;t11;zero;t11;zero;zero;zero;t11;zero;zero;zero;t11;zero;zero;zero;zero;zero;zero;zero;t11;zero;t11;zero;t10;zero;zero;zero;t10;zero;zero;zero;t14];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
