function [f,f_udg] = flux2d(pg,udg,param,time)
%FLUX2D
%    [F,F_UDG] = FLUX2D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    23-Jul-2017 23:10:56
[ng,nc] = size(udg);
nch = 2;
nd = 2;
one = ones(ng,1);
param1 = param{1};
param2 = param{2};
u3 = udg(:,3);
u4 = udg(:,4);
u5 = udg(:,5);
u6 = udg(:,6);
zero = zeros(ng,1);
t2 = u4+u5;
t3 = param1.*t2;
t4 = u3+u6;
t5 = param2.*t4;
f = [t5+param1.*u3.*2.0;t3;t3;t5+param1.*u6.*2.0];
if nargout > 1
    t6 = one.*param1;
    t7 = one.*param2;
    t8 = param1.*2.0;
    t9 = param2+t8;
    t10 = one.*t9;
    f_udg = [zero;zero;zero;zero;zero;zero;zero;zero;t10;zero;zero;t7;zero;t6;t6;zero;zero;t6;t6;zero;t7;zero;zero;t10];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
