function [f,f_udg] = flux2d2(pg,udg,param,time)
%FLUX2D2
%    [F,F_UDG] = FLUX2D2(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    28-Mar-2013 12:19:48
[ng,nc] = size(udg);
nch = 4;
nd = 2;
one = ones(ng,1);
param1 = param{1};
param9 = param{9};
u1 = udg(:,1);
u2 = udg(:,2);
u3 = udg(:,3);
u4 = udg(:,4);
zero = zeros(ng,1);
t2 = u2.^2;
t3 = 1.0./u1.^2;
t4 = 1.0./u1;
t5 = 1.0./param9;
t6 = t2.*t3.*(1.0./2.0);
t7 = u3.^2;
t8 = t3.*t7.*(1.0./2.0);
t9 = t6+t8;
t17 = t9.*u1;
t10 = -t17+u4;
t11 = param1-1.0;
t12 = t5.*t10.*t11.*2.0e1;
t13 = exp(t12);
t14 = t13+2.0e1;
t15 = log(t14);
t16 = t4.*u2.*u3;
t18 = param9.*t15.*(1.0./2.0e1);
t19 = t4.*u4;
t20 = param9.*t4.*t15.*(1.0./2.0e1);
t21 = t19+t20;
f = [u2;t18+t2.*t4;t16;t21.*u2;u3;t16;t18+t4.*t7;t21.*u3];
if nargout > 1
    t22 = 1.0./u1.^3;
    t23 = 1.0./t14;
    t24 = t2.*t22;
    t25 = t7.*t22;
    t26 = t24+t25;
    t28 = t26.*u1;
    t27 = t6+t8-t28;
    t29 = t3.*u4;
    t30 = param9.*t3.*t15.*(1.0./2.0e1);
    t31 = t4.*t11.*t13.*t23.*t27;
    t32 = t29+t30+t31;
    t33 = t4.*u3;
    t34 = t4.*u2;
    t35 = t11.*t13.*t23;
    t36 = t4.*t11.*t13.*t23;
    t37 = t4+t36;
    f_udg = [zero;-t2.*t3-t11.*t13.*t23.*t27;-t3.*u2.*u3;-t32.*u2;zero;-t3.*u2.*u3;-t3.*t7-t11.*t13.*t23.*t27;-t32.*u3;one;t4.*u2.*2.0-t4.*t11.*t13.*t23.*u2;t33;t19+t20-t2.*t3.*t11.*t13.*t23;zero;t33;-t4.*t11.*t13.*t23.*u2;-t3.*t11.*t13.*t23.*u2.*u3;zero;-t4.*t11.*t13.*t23.*u3;t34;-t3.*t11.*t13.*t23.*u2.*u3;one;t34;t4.*u3.*2.0-t4.*t11.*t13.*t23.*u3;t19+t20-t3.*t7.*t11.*t13.*t23;zero;t35;zero;t37.*u2;zero;zero;t35;t37.*u3;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
