function [fh,fh_udg,fh_uh] = fhat2d(nl,pg,udg,uh,param,time)
%FHAT2D
%    [FH,FH_UDG,FH_UH] = FHAT2D(NL,PG,UDG,UH,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Jul-2011 17:32:14
[ng,nc] = size(udg);
nch = 2;
nd = 2;
mu = param{1};
nl1 = nl(:,1);
nl2 = nl(:,2);
one = ones(ng,1);
pres = udg(:,3);
q11 = udg(:,4);
q12 = udg(:,6);
q21 = udg(:,5);
q22 = udg(:,7);
tau = param{3};
u1 = udg(:,1);
u2 = udg(:,2);
uh1 = uh(:,1);
uh2 = uh(:,2);
zero = zeros(ng,1);
t2020 = q11.*q22;
t2023 = q12.*q21;
t2021 = t2020-t2023;
t2022 = 1.0./t2021;
fh = [nl1.*(mu.*q11+pres.*q22-mu.*q22.*t2022)+nl2.*(mu.*q12-pres.*q21+mu.*q21.*t2022)+tau.*(u1-uh1);nl1.*(mu.*q21-pres.*q12+mu.*q12.*t2022)+nl2.*(mu.*q22+pres.*q11-mu.*q11.*t2022)+tau.*(u2-uh2)];
if nargout > 1
    t2024 = one.*tau;
    t2025 = 1.0./t2021.^2;
    t2026 = mu.*t2022;
    t2027 = mu.*q12.*q21.*t2025;
    t2028 = -pres+t2026+t2027;
    t2029 = mu.*q11.*q22.*t2025;
    fh_udg = [t2024;zero;zero;t2024;nl1.*q22-nl2.*q21;-nl1.*q12+nl2.*q11;nl1.*(mu+mu.*q22.^2.*t2025)-mu.*nl2.*q21.*q22.*t2025;nl2.*(pres+t2029-mu.*t2022)-mu.*nl1.*q12.*q22.*t2025;nl2.*t2028-mu.*nl1.*q12.*q22.*t2025;nl1.*(mu+mu.*q12.^2.*t2025)-mu.*nl2.*q11.*q12.*t2025;nl2.*(mu+mu.*q21.^2.*t2025)-mu.*nl1.*q21.*q22.*t2025;nl1.*t2028-mu.*nl2.*q11.*q21.*t2025;nl1.*(pres-t2026+t2029)-mu.*nl2.*q11.*q21.*t2025;nl2.*(mu+mu.*q11.^2.*t2025)-mu.*nl1.*q11.*q12.*t2025];
end
if nargout > 2
    fh_uh = [-t2024;zero;zero;-t2024];
end
fh = reshape(fh,ng,nch);
fh_udg = reshape(fh_udg,ng,nch,nc);
fh_uh = reshape(fh_uh,ng,nch,nch);
