function [f,f_udg] = flux2d(pg,udg,param,time)
%FLUX2D
%    [F,F_UDG] = FLUX2D(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 5.4.
%    10-Jul-2011 17:32:12
[ng,nc] = size(udg);
nch = 2;
nd = 2;
mu = param{1};
pres = udg(:,3);
q11 = udg(:,4);
q12 = udg(:,6);
q21 = udg(:,5);
q22 = udg(:,7);
zero = zeros(ng,1);
t2010 = q11.*q22;
t2013 = q12.*q21;
t2011 = t2010-t2013;
t2012 = 1.0./t2011;
f = [mu.*q11+pres.*q22-mu.*q22.*t2012;mu.*q21-pres.*q12+mu.*q12.*t2012;mu.*q12-pres.*q21+mu.*q21.*t2012;mu.*q22+pres.*q11-mu.*q11.*t2012];
if nargout > 1
    t2014 = 1.0./t2011.^2;
    t2015 = mu.*t2012;
    t2016 = mu.*q12.*q21.*t2014;
    t2017 = -pres+t2015+t2016;
    t2018 = mu.*q11.*q22.*t2014;
    f_udg = [zero;zero;zero;zero;zero;zero;zero;zero;q22;-q12;-q21;q11;mu+mu.*q22.^2.*t2014;-mu.*q12.*q22.*t2014;-mu.*q21.*q22.*t2014;pres+t2018-mu.*t2012;-mu.*q12.*q22.*t2014;mu+mu.*q12.^2.*t2014;t2017;-mu.*q11.*q12.*t2014;-mu.*q21.*q22.*t2014;t2017;mu+mu.*q21.^2.*t2014;-mu.*q11.*q21.*t2014;pres-t2015+t2018;-mu.*q11.*q12.*t2014;-mu.*q11.*q21.*t2014;mu+mu.*q11.^2.*t2014];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
