function [f,f_udg] = flux2d1(pg,udg,param,time)
%FLUX2D1
%    [F,F_UDG] = FLUX2D1(PG,UDG,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 5.8.
%    26-Mar-2013 22:22:43
[ng,nc] = size(udg);
nch = 4;
nd = 2;
one = ones(ng,1);
param1 = param{1};
u1 = udg(:,1);
u2 = udg(:,2);
u3 = udg(:,3);
u4 = udg(:,4);
zero = zeros(ng,1);
t2 = u2.^2;
t3 = 1.0./u1.^2;
t4 = 1.0./u1;
t5 = t2.*t3.*(1.0./2.0);
t6 = u3.^2;
t7 = t3.*t6.*(1.0./2.0);
t8 = t5+t7;
t12 = t8.*u1;
t9 = -t12+u4;
t10 = param1-1.0;
t11 = t4.*u2.*u3;
t13 = t9.*t10;
t14 = t4.*u4;
t15 = t4.*t9.*t10;
t16 = t14+t15;
f = [u2;t13+t2.*t4;t11;t16.*u2;u3;t11;t13+t4.*t6;t16.*u3];
if nargout > 1
    t17 = 1.0./u1.^3;
    t18 = t2.*t17;
    t19 = t6.*t17;
    t20 = t18+t19;
    t22 = t20.*u1;
    t21 = t5+t7-t22;
    t23 = t3.*u4;
    t24 = t3.*t9.*t10;
    t25 = t4.*t10.*t21;
    t26 = t23+t24+t25;
    t27 = t4.*u3;
    t28 = t4.*u2;
    t29 = one.*t10;
    t30 = t4.*t10;
    t31 = t4+t30;
    f_udg = [zero;-t2.*t3-t10.*t21;-t3.*u2.*u3;-t26.*u2;zero;-t3.*u2.*u3;-t3.*t6-t10.*t21;-t26.*u3;one;t4.*u2.*2.0-t4.*t10.*u2;t27;t14+t15-t2.*t3.*t10;zero;t27;-t4.*t10.*u2;-t3.*t10.*u2.*u3;zero;-t4.*t10.*u3;t28;-t3.*t10.*u2.*u3;one;t28;t4.*u3.*2.0-t4.*t10.*u3;t14+t15-t3.*t6.*t10;zero;t29;zero;t31.*u2;zero;zero;t29;t31.*u3;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero];
end
f = reshape(f,ng,nch,nd);
f_udg = reshape(f_udg,ng,nch,nd,nc);
