function [fh,fh_udg,fh_uh] = fhat_euler2d(nl,pg,udg,uh,param,time)
%FHAT_EULER2D
%    [FH,FH_UDG,FH_UH] = FHAT_EULER2D(NL,PG,UDG,UH,PARAM,TIME)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    29-Sep-2017 12:01:06
[ng,nc] = size(udg);
nch = 4;
nd = 2;
one = ones(ng,1);
param1 = param{1};
uh1 = uh(:,1);
uh2 = uh(:,2);
uh3 = uh(:,3);
uh4 = uh(:,4);
zero = zeros(ng,1);
t2 = uh2.^2;
t3 = 1.0./uh1.^2;
t4 = 1.0./uh1;
t5 = t2.*t3.*(1.0./2.0);
t6 = uh3.^2;
t7 = t3.*t6.*(1.0./2.0);
t8 = t5+t7;
t12 = t8.*uh1;
t9 = -t12+uh4;
t10 = param1-1.0;
t11 = one.*t4.*uh2.*uh3;
t13 = t9.*t10;
t14 = t4.*uh4;
t15 = t4.*t9.*t10;
t16 = t14+t15;
fh = [one.*uh2;one.*(t13+t2.*t4);t11;one.*t16.*uh2;one.*uh3;t11;one.*(t13+t4.*t6);one.*t16.*uh3];
if nargout > 1
    fh_udg = [zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero;zero];
end
if nargout > 2
    t17 = 1.0./uh1.^3;
    t18 = t2.*t17;
    t19 = t6.*t17;
    t20 = t18+t19;
    t22 = t20.*uh1;
    t21 = t5+t7-t22;
    t23 = t10.*t21;
    t24 = t3.*uh4;
    t25 = t3.*t9.*t10;
    t26 = t4.*t10.*t21;
    t27 = t24+t25+t26;
    t28 = one.*t4.*uh3;
    t29 = one.*t4.*uh2;
    t30 = one.*t10;
    t31 = t4.*t10;
    t32 = t4+t31;
    fh_uh = [zero;-one.*(t23+t2.*t3);-one.*t3.*uh2.*uh3;-one.*t27.*uh2;zero;-one.*t3.*uh2.*uh3;-one.*(t23+t3.*t6);-one.*t27.*uh3;one;one.*(t4.*uh2.*2.0-t4.*t10.*uh2);t28;one.*(t14+t15-t2.*t3.*t10);zero;t28;-one.*t4.*t10.*uh2;-one.*t3.*t10.*uh2.*uh3;zero;-one.*t4.*t10.*uh3;t29;-one.*t3.*t10.*uh2.*uh3;one;t29;one.*(t4.*uh3.*2.0-t4.*t10.*uh3);one.*(t14+t15-t3.*t6.*t10);zero;t30;zero;one.*t32.*uh2;zero;zero;t30;one.*t32.*uh3];
end
fh = reshape(fh,ng,nch);
fh_udg = reshape(fh_udg,ng,nch,nc);
fh_uh = reshape(fh_uh,ng,nch,nch);
